export { ProblemSolutionSection } from "./problem-solution-section";
export { ProblemCard } from "./problem-card";
export { SolutionCard } from "./solution-card";
export { ConnectorLine } from "./connector-line";
export { SectionHeader } from "./section-header";
export { SectionCta } from "./section-cta";
export { ProblemsColumn } from "./problems-column";
export { SolutionsColumn } from "./solutions-column";
export type { ProblemSolutionCardProps, Problem, Solution } from "./types";
export { problems, solutions } from "./data";