import { getPredictionJob } from "@/lib/api";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

interface JobsPageProps {
  searchParams: { job_id?: string | string[] };
}

export default async function JobsPage({ searchParams }: JobsPageProps) {
  const jobId = Array.isArray(searchParams.job_id) ? searchParams.job_id[0] : searchParams.job_id;
  let job = null;
  let errorMessage: string | null = null;

  if (jobId) {
    try {
      job = await getPredictionJob(jobId);
    } catch (error) {
      errorMessage = error instanceof Error ? error.message : "Unable to fetch job details.";
    }
  }

  return (
    <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">
      <div className="mb-8">
        <p className="text-sm uppercase tracking-[0.24em] text-muted-foreground">Job Lookup</p>
        <h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">
          Inspect queue job state
        </h1>
        <p className="mt-3 text-base leading-7 text-muted-foreground max-w-2xl">
          Enter a prediction job ID to view its status, attempt history, and backend result payload.
        </p>
      </div>

      <Card className="border border-border p-6">
        <form className="grid gap-4 sm:grid-cols-[1fr_auto]" action="." method="get">
          <label className="sr-only" htmlFor="job_id">
            Prediction job ID
          </label>
          <input
            id="job_id"
            name="job_id"
            defaultValue={jobId ?? ""}
            placeholder="Prediction job ID"
            className="w-full rounded-xl border border-input bg-background px-4 py-3 text-base text-foreground shadow-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20"
          />
          <button
            type="submit"
            className="inline-flex items-center justify-center rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground transition hover:bg-primary/90"
          >
            Load job
          </button>
        </form>
      </Card>

      {errorMessage ? (
        <div className="mt-6 rounded-3xl border border-destructive/30 bg-destructive/10 p-6 text-sm text-destructive">
          {errorMessage}
        </div>
      ) : null}

      {job ? (
        <div className="mt-8 grid gap-6 lg:grid-cols-2">
          <Card className="border border-border">
            <CardHeader className="px-6 py-5">
              <CardTitle>Job metadata</CardTitle>
              <CardDescription>Status, attempts, and queue metadata.</CardDescription>
            </CardHeader>
            <CardContent className="px-6 pb-6 pt-0 space-y-4">
              <div>
                <p className="text-sm text-muted-foreground">Status</p>
                <Badge variant={job.status === "completed" ? "default" : job.status === "failed" ? "destructive" : "secondary"}>
                  {job.status}
                </Badge>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Attempts</p>
                <p className="mt-1 text-lg font-semibold">{job.attempts} / {job.max_attempts}</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Last error</p>
                <p className="mt-1 text-lg font-semibold">{job.last_error ?? "None"}</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Queued at</p>
                <p className="mt-1 text-lg font-semibold">{job.queued_at ?? "—"}</p>
              </div>
            </CardContent>
          </Card>

          <Card className="border border-border">
            <CardHeader className="px-6 py-5">
              <CardTitle>Related prediction</CardTitle>
              <CardDescription>Reference IDs generated by the backend.</CardDescription>
            </CardHeader>
            <CardContent className="px-6 pb-6 pt-0 space-y-4">
              <div>
                <p className="text-sm text-muted-foreground">Prediction record</p>
                <p className="mt-1 text-lg font-semibold">{job.prediction_record_id ?? "Pending"}</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Feature snapshot</p>
                <p className="mt-1 text-lg font-semibold">{job.feature_snapshot_id ?? "N/A"}</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Student profile</p>
                <p className="mt-1 text-lg font-semibold">{job.student_profile_id}</p>
              </div>
            </CardContent>
          </Card>

          <Card className="lg:col-span-2 border border-border">
            <CardHeader className="px-6 py-5">
              <CardTitle>Job result payload</CardTitle>
              <CardDescription>Raw result contents from the backend / prediction job entry.</CardDescription>
            </CardHeader>
            <CardContent className="px-6 pb-6 pt-0">
              <pre className="overflow-x-auto rounded-3xl border border-border bg-muted/50 p-5 text-sm text-muted-foreground">
                {JSON.stringify(job.result, null, 2)}
              </pre>
            </CardContent>
          </Card>
        </div>
      ) : jobId ? (
        <div className="mt-8 rounded-3xl border border-border bg-muted/50 p-6 text-sm text-muted-foreground">
          The job ID was submitted but no details could be loaded.
        </div>
      ) : null}
    </div>
  );
}
